# Site Settings
locale: "en-US"
title: "Greg Svensson"
title_separator: "-"
subtitle: "Greg Svensson"
name: "Greg Svensson"
description: "Greg Svensson - Projects and CV"
baseurl: "spring-2025-portfolio-gregsvensson"  # CHANGE to your repo name
url: "https://cornell-mae-ug.github.io"

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light

sass:
  style: compressed

# Output structure
permalink: /:categories/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Defaults for assets
defaults:
  - scope:
      path: "assets"
    values:
      permalink: "{{ site.baseurl }}/assets/:path"
